version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nom_db
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    network_mode: "host"
    build: ./backend
    ports:
      - "8000:8000"
volumes:
  dbdata:
