version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nom_db
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    image: lanuitdelinfo-backend
    build: ./backend
    network_mode: "host"
    ports:
      - "8000:8000"
  frontend:
    image: lanuitdelinfo-frontend
    build: ./frontend
    network_mode: "host"
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
volumes:
  dbdata:
