version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nom_db
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  dbdata:
