version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nuitdelinfo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    image: lanuitdelinfo-backend
    build: ./backend
    network_mode: "host"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  frontend:
    image: lanuitdelinfo-frontend
    build: ./frontend
    network_mode: "host"
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
volumes:
  dbdata:
