version: "3"
services:
  db:
    image: postgres
    network_mode: "host"
    environment:
      POSTGRES_DB: nuitdelinfo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
volumes:
  dbdata:
