version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nom_db
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    networks: 
      - app-network
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks: 
      - app-network
volumes:
  dbdata:
networks:
  app-network:
    driver: bridge