version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nom_db
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    network_mode: "host"
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    network_mode: "host"
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
  monservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: lanuitdelinfo:latest

volumes:
  dbdata:
