name: Server Build & Push

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd nuit-info-actix
            git pull
            docker compose -f docker-compose.prod.yml build

